### ISSUE TITLE
UI/UX mockups

### ISSUE THREAD

**Issue by mcereal** [TomatoPals/PomoDuck#13]
- [ ] Homepage
- [ ] Navigation Menu
- [ ] settings
- [ ] Profile
- [ ] stats/leaderboard
- [ ] signup/login

**Comment by singletree-digital** [comment]
@pmhagwood  Check this out

**Comment by singletree-digital** [comment]
@pmhagwood @bartcusick 

Here is what I was playing with at least a little.  

[PomoDuck Project Login.pdf](https://github.com/TomatoPals/PomoDuck/files/5914620/PomoDuck.Project.Login.pdf)
[PomoDuck Project Homepage.pdf](https://github.com/TomatoPals/PomoDuck/files/5914621/PomoDuck.Project.Homepage.pdf)

**Comment by singletree-digital** [comment]
@pmhagwood @bartcusick 

More stuff 

[PomoDuck Project Timer 1.pdf](https://github.com/TomatoPals/PomoDuck/files/5914775/PomoDuck.Project.Timer.1.pdf)
[PomoDuck Project Timer 2.pdf](https://github.com/TomatoPals/PomoDuck/files/5914776/PomoDuck.Project.Timer.2.pdf)
[PomoDuck Project Timer 3.pdf](https://github.com/TomatoPals/PomoDuck/files/5914777/PomoDuck.Project.Timer.3.pdf)
